apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-world
  labels:
    {{- include "hello-world-pdb.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
      app.kubernetes.io/instance: {{ .Release.Name }}