apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    {{- include "hello-world-pdb.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
    
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: {{ .Release.Name }}